import { useRouter } from 'expo-router';
import { CalendarDays, FileText } from 'lucide-react-native';
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/components/layout/AppHeader';
import { OrganizationLogo } from '@/components/job/OrganizationLogo';
import { EmptyState } from '@/components/ui/EmptyState';
import { ScreenContainer } from '@/components/ui/ScreenContainer';
import { colors } from '@/constants/colors';
import { useExamNotices } from '@/hooks/useExamNotices';
import type { ExamNotice } from '@/types/examNotice';
import { formatJobDate } from '@/utils/date';

const EMBLEM = require('@/assets/images/bd-government-emblem.jpg');
const labels = { exam_schedule: 'পরীক্ষার সময়সূচি', admit_card: 'প্রবেশপত্র', result: 'ফলাফল', other: 'বিজ্ঞপ্তি' } as const;
export default function ExamsScreen() { const router = useRouter(); const query = useExamNotices(); return <ScreenContainer><FlatList data={query.data ?? []} keyExtractor={(item) => String(item.id)} renderItem={({ item }) => <NoticeCard item={item} onOpen={() => item.circular_url && router.push({ pathname: '/pdf', params: { url: item.circular_url, title: item.title } })} />} ItemSeparatorComponent={() => <View style={styles.gap} />} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} tintColor={colors.primary} />} ListHeaderComponent={<View style={styles.header}><AppHeader logo={EMBLEM} topText="গণপ্রজাতন্ত্রী বাংলাদেশ সরকার" title="পরীক্ষা ও প্রবেশপত্র" subtitle="পরীক্ষার সময়সূচি, প্রবেশপত্র ও ফলাফল" /></View>} ListEmptyComponent={query.isLoading ? <Text style={styles.loading}>তথ্য লোড হচ্ছে…</Text> : query.isError ? <EmptyState title="পরীক্ষার তথ্য লোড করা যাচ্ছে না" actionLabel="আবার চেষ্টা করুন" onAction={() => void query.refetch()} /> : <EmptyState title="নতুন পরীক্ষা বা প্রবেশপত্র নেই" message="অফিসিয়াল বিজ্ঞপ্তি প্রকাশ হলে এখানে দেখা যাবে।" />} /></ScreenContainer>; }
function NoticeCard({ item, onOpen }: { item: ExamNotice; onOpen: () => void }) { return <View style={styles.card}><View style={styles.top}><OrganizationLogo name={item.organization} logoUrl={item.organization_logo_url} /><View style={styles.copy}><Text style={styles.org}>{item.organization}</Text><Text style={styles.type}>{labels[item.notice_type]}</Text></View></View><Text style={styles.title}>{item.title}</Text><View style={styles.dates}><CalendarDays size={15} color={colors.primary} /><Text style={styles.date}>প্রকাশ: {formatJobDate(item.published_date) || 'উল্লেখ নেই'}</Text>{item.exam_date ? <Text style={styles.examDate}>পরীক্ষা: {formatJobDate(item.exam_date)}</Text> : null}</View>{item.circular_url ? <Pressable style={styles.button} onPress={onOpen}><FileText size={17} color="#fff" /><Text style={styles.buttonText}>বিজ্ঞপ্তি দেখুন</Text></Pressable> : null}</View>; }
const styles = StyleSheet.create({ content: { flexGrow: 1, padding: 16, paddingBottom: 30 }, header: { marginBottom: 18 }, gap: { height: 12 }, loading: { color: colors.textSecondary, textAlign: 'center', marginTop: 50 }, card: { padding: 16, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card }, top: { flexDirection: 'row', alignItems: 'center', gap: 10 }, copy: { flex: 1 }, org: { color: colors.primaryDeep, fontSize: 13, fontWeight: '800' }, type: { color: colors.primary, fontSize: 10, fontWeight: '700', marginTop: 4 }, title: { color: colors.text, fontSize: 16, lineHeight: 23, fontWeight: '800', marginTop: 13 }, dates: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 7, marginTop: 13, padding: 10, borderRadius: 10, backgroundColor: colors.primaryLight }, date: { color: colors.textSecondary, fontSize: 11 }, examDate: { color: colors.primaryDeep, fontSize: 11, fontWeight: '800', marginLeft: 'auto' }, button: { alignSelf: 'flex-start', minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 14, borderRadius: 10, backgroundColor: colors.primary, marginTop: 13 }, buttonText: { color: '#fff', fontSize: 12, fontWeight: '800' } });
