import { useRef } from 'react';
import LottieView from 'lottie-react-native';
import { BriefcaseBusiness, ChevronRight, FileCheck2, Globe2, RefreshCw } from 'lucide-react-native';
import { Dimensions, FlatList, Image, Pressable, StyleSheet, Text, View, type ViewToken } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '@/constants/colors';
import { useOnboarding } from '@/hooks/useOnboarding';

const width = Dimensions.get('window').width;
const EMBLEM = require('@/assets/images/bd-government-emblem.jpg');
const slides = [
  { key: 'problem', icon: Globe2, eyebrow: 'একটি পরিচিত সমস্যা', title: 'চাকরি খুঁজতে আর নয়\nwebsite থেকে website', text: 'মন্ত্রণালয় ও সরকারি দপ্তরের অসংখ্য website ঘুরে সঠিক নিয়োগ বিজ্ঞপ্তি খোঁজা সময়সাপেক্ষ। গুরুত্বপূর্ণ circular চোখ এড়িয়ে যাওয়ার দুশ্চিন্তাও থাকে।' },
  { key: 'solution', icon: FileCheck2, eyebrow: 'আপনার জন্য সহজ সমাধান', title: 'চাকরি, যোগ্যতা ও circular\nএখন একই platform-এ', text: 'বিভিন্ন সরকারি প্রতিষ্ঠানের প্রকাশিত চাকরি, আবেদনের যোগ্যতা, শেষ তারিখ এবং official PDF সাজানোভাবে দেখুন—এক জায়গা থেকেই।' },
  { key: 'updates', icon: RefreshCw, eyebrow: 'নিয়মিত তথ্য সংগ্রহ', title: 'প্রতিদিনের update-এ\nএগিয়ে থাকুন', text: 'নতুন চাকরি, শেষ সময়, পরীক্ষা ও প্রবেশপত্রের প্রকাশিত তথ্য নিয়মিত সংগ্রহ করি—আপনার সময় বাঁচাতে এবং সুযোগ খুঁজে পেতে।' },
] as const;

export default function OnboardingScreen() {
  const list = useRef<FlatList>(null); const { index, setIndex, saving, complete, next, isLast } = useOnboarding(slides.length);
  const onViewableItemsChanged = useRef(({ viewableItems }: { viewableItems: ViewToken[] }) => { const nextIndex = viewableItems[0]?.index; if (nextIndex !== null && nextIndex !== undefined) setIndex(nextIndex); }).current;
  return <SafeAreaView style={styles.safe}><View style={styles.flagLine}><View style={styles.flagGreen} /><View style={styles.flagRed} /></View><View style={styles.top}><View style={styles.brand}><Image source={EMBLEM} style={styles.emblem} /><View><Text style={styles.gov}>সরকারি চাকরির তথ্যসেবা</Text><Text style={styles.brandTitle}>Govt Jobs BD</Text></View></View><Pressable accessibilityRole="button" onPress={() => void complete()} style={styles.skip}><Text style={styles.skipText}>এড়িয়ে যান</Text></Pressable></View><FlatList ref={list} data={slides} horizontal pagingEnabled showsHorizontalScrollIndicator={false} keyExtractor={(item) => item.key} onViewableItemsChanged={onViewableItemsChanged} viewabilityConfig={{ itemVisiblePercentThreshold: 60 }} renderItem={({ item }) => { const Icon = item.icon; return <View style={styles.slide}><View style={styles.art}><LottieView autoPlay loop source={require('@/assets/animations/govt-service.json')} style={styles.lottie} /><View style={styles.slideIcon}><Icon size={28} color={colors.primary} /></View><View style={styles.miniBadge}><BriefcaseBusiness size={17} color="#fff" /></View></View><Text style={styles.eyebrow}>{item.eyebrow}</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.text}>{item.text}</Text><View style={styles.trust}><FileCheck2 size={15} color={colors.primary} /><Text style={styles.trustText}>প্রকাশিত source ও circular যাচাইয়ের সুবিধা</Text></View></View>; }} /><View style={styles.bottom}><View style={styles.dots}>{slides.map((slide, dot) => <View key={slide.key} style={[styles.dot, dot === index && styles.dotActive]} />)}</View><Pressable accessibilityRole="button" disabled={saving} style={styles.next} onPress={() => next((nextIndex) => list.current?.scrollToIndex({ index: nextIndex, animated: true }))}><Text style={styles.nextText}>{isLast ? 'চাকরি খোঁজা শুরু করুন' : 'পরবর্তী'}</Text><ChevronRight size={20} color="#fff" /></Pressable><Text style={styles.disclaimer}>এটি একটি স্বাধীন তথ্যসংগ্রাহক platform—আবেদনের আগে official circular যাচাই করুন।</Text></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#fff' }, flagLine: { height: 4, flexDirection: 'row' }, flagGreen: { flex: 1, backgroundColor: colors.primary }, flagRed: { width: 48, backgroundColor: colors.red }, top: { minHeight: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18 }, brand: { flexDirection: 'row', alignItems: 'center', gap: 8 }, emblem: { width: 40, height: 40, borderRadius: 20 }, gov: { color: '#34684F', fontSize: 8.5, fontWeight: '700' }, brandTitle: { color: colors.primaryDeep, fontSize: 16, fontWeight: '900', marginTop: 1 }, skip: { minHeight: 40, justifyContent: 'center', paddingHorizontal: 8 }, skipText: { color: colors.primary, fontSize: 12, fontWeight: '800' }, slide: { width, alignItems: 'center', paddingHorizontal: 28, paddingTop: 20 }, art: { width: 250, height: 250, alignItems: 'center', justifyContent: 'center', marginBottom: 20 }, lottie: { width: 250, height: 250 }, slideIcon: { position: 'absolute', width: 58, height: 58, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#C8E9DC' }, miniBadge: { position: 'absolute', right: 15, bottom: 25, width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary, borderWidth: 4, borderColor: '#fff' }, eyebrow: { color: colors.primary, fontSize: 12, fontWeight: '900', marginBottom: 9 }, title: { color: colors.text, fontSize: 26, lineHeight: 37, fontWeight: '900', textAlign: 'center' }, text: { color: colors.textSecondary, fontSize: 13.5, lineHeight: 22, textAlign: 'center', marginTop: 13, maxWidth: 335 }, trust: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 11, paddingVertical: 7, borderRadius: 10, backgroundColor: colors.primaryLight, marginTop: 14 }, trustText: { color: colors.primaryDeep, fontSize: 9.5, fontWeight: '700' }, bottom: { paddingHorizontal: 22, paddingBottom: 12, alignItems: 'center' }, dots: { height: 22, flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 8 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.border }, dotActive: { width: 24, backgroundColor: colors.primary }, next: { width: '100%', minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 14, backgroundColor: colors.primary }, nextText: { color: '#fff', fontSize: 14, fontWeight: '900' }, disclaimer: { color: colors.textSecondary, fontSize: 9, lineHeight: 14, textAlign: 'center', marginTop: 10 } });
