import { useRouter } from 'expo-router';
import { Bookmark, BriefcaseBusiness, ChevronLeft, Clock3, Sparkles } from 'lucide-react-native';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '@/constants/colors';
import { useHomeStats } from '@/hooks/useJobs';
import { useSavedJobsStore } from '@/store/savedJobs.store';
import { toBanglaDigits } from '@/utils/date';

export default function OverviewScreen() {
  const router = useRouter(); const stats = useHomeStats(); const saved = useSavedJobsStore((state) => state.savedJobIds.length);
  const go = (params?: Record<string, string>) => router.push({ pathname: '/jobs', params });
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable style={styles.back} onPress={router.back}><ChevronLeft size={25} color={colors.text} /></Pressable><View><Text style={styles.title}>চাকরির সারসংক্ষেপ</Text><Text style={styles.subtitle}>আপনার প্রয়োজন অনুযায়ী তালিকা খুলুন</Text></View></View><ScrollView contentContainerStyle={styles.content}><OverviewCard icon={BriefcaseBusiness} title="মোট চলমান চাকরি" value={stats.data?.active} onPress={() => go()} /><OverviewCard icon={Sparkles} title="গত ৭ দিনের নতুন চাকরি" value={stats.data?.recent} onPress={() => go({ published: '7' })} /><OverviewCard icon={Clock3} title="৭ দিনের মধ্যে শেষ হবে" value={stats.data?.closing} urgent onPress={() => go({ deadline: '7' })} /><OverviewCard icon={Bookmark} title="আপনার সংরক্ষিত চাকরি" value={saved} onPress={() => router.push('/saved')} /><Pressable style={styles.categories} onPress={() => router.push('/categories')}><Text style={styles.categoriesTitle}>বিভাগ অনুযায়ী খুঁজুন</Text><Text style={styles.categoriesText}>সব চাকরির বিভাগ ও সংশ্লিষ্ট নিয়োগ দেখুন</Text></Pressable></ScrollView></SafeAreaView>;
}
function OverviewCard({ icon: Icon, title, value, urgent, onPress }: { icon: typeof BriefcaseBusiness; title: string; value?: number; urgent?: boolean; onPress: () => void }) { return <Pressable style={styles.card} onPress={onPress}><View style={[styles.icon, urgent && styles.urgentIcon]}><Icon size={24} color={urgent ? colors.warning : colors.primary} /></View><View style={styles.copy}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.hint}>তালিকা দেখতে চাপুন</Text></View><Text style={[styles.value, urgent && styles.urgent]}>{value === undefined ? '—' : toBanglaDigits(value)}</Text></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#fff' }, header: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 10, borderBottomWidth: 1, borderBottomColor: colors.border }, back: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.primaryDeep, fontSize: 20, fontWeight: '900' }, subtitle: { color: colors.textSecondary, fontSize: 10, marginTop: 2 }, content: { padding: 16, gap: 12 }, card: { minHeight: 90, flexDirection: 'row', alignItems: 'center', gap: 13, padding: 15, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card }, icon: { width: 50, height: 50, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primaryLight }, urgentIcon: { backgroundColor: colors.warningLight }, copy: { flex: 1 }, cardTitle: { color: colors.text, fontSize: 14, fontWeight: '800' }, hint: { color: colors.textSecondary, fontSize: 10, marginTop: 4 }, value: { color: colors.primary, fontSize: 25, fontWeight: '900' }, urgent: { color: colors.warning }, categories: { padding: 18, borderRadius: 14, backgroundColor: colors.primaryDeep, marginTop: 4 }, categoriesTitle: { color: '#fff', fontSize: 16, fontWeight: '900' }, categoriesText: { color: '#D7EEE6', fontSize: 11, marginTop: 5 } });
