-- Supabase Database Setup for Bangladesh Government Job Scraper

-- Create jobs table
CREATE TABLE jobs (
    id bigint generated by default as identity primary key,
    title text not null,
    organization text not null,
    category text,
    
    published_date date,
    deadline date,
    
    vacancies integer,
    employment_type text,
    
    education text,
    experience text,
    age_requirement text,
    
    location text,
    salary text,
    description text,
    
    source text not null,
    source_url text not null,
    apply_url text,
    circular_url text,
    
    is_active boolean default true not null,
    external_id text, -- fingerprint (sha256 of org+title+deadline)
    
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

-- Unique constraint for source and source_url combination
ALTER TABLE jobs ADD CONSTRAINT jobs_source_url_key UNIQUE (source, source_url);

-- Unique constraint for external_id (fingerprint)
ALTER TABLE jobs ADD CONSTRAINT jobs_external_id_key UNIQUE (external_id);

-- Create indexes for common query patterns
CREATE INDEX idx_jobs_is_active ON jobs(is_active);
CREATE INDEX idx_jobs_deadline ON jobs(deadline);
CREATE INDEX idx_jobs_published_date ON jobs(published_date);
CREATE INDEX idx_jobs_organization ON jobs(organization);
CREATE INDEX idx_jobs_source ON jobs(source);

-- Trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_jobs_modtime
    BEFORE UPDATE ON jobs
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- Row Level Security (RLS) setup (for the mobile app to read safely)
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- Allow read access to anyone (anon key)
CREATE POLICY "Allow public read access"
ON jobs
FOR SELECT
TO anon, authenticated
USING (true);

-- The scraper uses the service_role key, which bypasses RLS automatically.
