-- Supabase Database Setup for Bangladesh Government Job Scraper

-- Create jobs table
CREATE TABLE jobs (
    id bigint generated by default as identity primary key,
    title text not null,
    organization text not null,
    organization_logo_url text,
    is_government_source boolean default true not null,
    category text,
    
    published_date date,
    deadline date,
    
    vacancies integer,
    employment_type text,
    
    education text,
    experience text,
    age_requirement text,
    eligibility_summary text,
    eligible_applicants text,
    qualification_tags text[] default '{}' not null,
    
    location text,
    salary text,
    description text,
    
    source text not null,
    source_url text not null,
    apply_url text,
    circular_url text,
    
    is_active boolean default true not null,
    external_id text, -- fingerprint (sha256 of org+title+deadline)
    
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

-- Unique constraint for source and source_url combination
ALTER TABLE jobs ADD CONSTRAINT jobs_source_url_key UNIQUE (source, source_url);

-- Unique constraint for external_id (fingerprint)
ALTER TABLE jobs ADD CONSTRAINT jobs_external_id_key UNIQUE (external_id);

-- Create indexes for common query patterns
CREATE INDEX idx_jobs_is_active ON jobs(is_active);
CREATE INDEX idx_jobs_deadline ON jobs(deadline);
CREATE INDEX idx_jobs_published_date ON jobs(published_date);
CREATE INDEX idx_jobs_organization ON jobs(organization);
CREATE INDEX idx_jobs_is_government_source ON jobs(is_government_source);
CREATE INDEX idx_jobs_source ON jobs(source);
CREATE INDEX idx_jobs_qualification_tags ON jobs USING gin (qualification_tags);

-- Trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_jobs_modtime
    BEFORE UPDATE ON jobs
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- Row Level Security (RLS) setup (for the mobile app to read safely)
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- Allow read access to anyone (anon key)
CREATE POLICY "Allow public read access"
ON jobs
FOR SELECT
TO anon, authenticated
USING (true);

CREATE TABLE exam_notices (
    id bigint generated by default as identity primary key,
    title text not null,
    organization text not null,
    organization_logo_url text,
    notice_type text not null check (notice_type in ('exam_schedule', 'admit_card', 'result', 'other')),
    published_date date,
    exam_date date,
    description text,
    source text not null,
    source_url text not null,
    circular_url text,
    is_active boolean default true not null,
    external_id text unique not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    unique (source, source_url)
);
CREATE INDEX idx_exam_notices_published ON exam_notices(published_date DESC);
CREATE INDEX idx_exam_notices_exam_date ON exam_notices(exam_date);
ALTER TABLE exam_notices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public exam notice read access" ON exam_notices FOR SELECT TO anon, authenticated USING (true);

-- The scraper uses the service_role key, which bypasses RLS automatically.
