CREATE TABLE IF NOT EXISTS exam_notices (
    id bigint generated by default as identity primary key,
    title text not null, organization text not null, organization_logo_url text,
    notice_type text not null check (notice_type in ('exam_schedule', 'admit_card', 'result', 'other')),
    published_date date, exam_date date, description text,
    source text not null, source_url text not null, circular_url text,
    is_active boolean default true not null, external_id text unique not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    unique (source, source_url)
);
CREATE INDEX IF NOT EXISTS idx_exam_notices_published ON exam_notices(published_date DESC);
CREATE INDEX IF NOT EXISTS idx_exam_notices_exam_date ON exam_notices(exam_date);
ALTER TABLE exam_notices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public exam notice read access" ON exam_notices;
CREATE POLICY "Allow public exam notice read access" ON exam_notices FOR SELECT TO anon, authenticated USING (true);
