-- Idempotent release migration for the current mobile app and scraper.
-- Run this single file in the Supabase SQL Editor for an existing database.

ALTER TABLE jobs
    ADD COLUMN IF NOT EXISTS organization_logo_url text,
    ADD COLUMN IF NOT EXISTS is_government_source boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS eligibility_summary text,
    ADD COLUMN IF NOT EXISTS eligible_applicants text,
    ADD COLUMN IF NOT EXISTS qualification_tags text[] NOT NULL DEFAULT '{}';

CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_external_id_unique
    ON jobs(external_id) WHERE external_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_jobs_is_government_source
    ON jobs(is_government_source);
CREATE INDEX IF NOT EXISTS idx_jobs_qualification_tags ON jobs USING gin (qualification_tags);

UPDATE jobs SET is_government_source = true
WHERE lower(source_url) ~ '^https?://([^/]+\.)?gov\.bd(/|$)'
   OR lower(source_url) ~ '^https?://([^/]+\.)?teletalk\.com\.bd(/|$)';

UPDATE jobs SET organization_logo_url = NULL
WHERE lower(coalesce(organization_logo_url, '')) SIMILAR TO
      '%(bangladesh-government-logo|bangladesh-govt-logo|govt-logo|government-logo|national-portal|emblem)%';

UPDATE jobs SET category = 'রেলওয়ে' WHERE source = 'Bangladesh Railway' AND category IS NULL;
UPDATE jobs SET category = 'স্বাস্থ্য' WHERE source = 'DGHS' AND category IS NULL;
UPDATE jobs SET category = 'শিক্ষা' WHERE source = 'SHED' AND category IS NULL;
UPDATE jobs SET category = 'জনপ্রশাসন' WHERE source = 'BPSC' AND category IS NULL;

CREATE TABLE IF NOT EXISTS exam_notices (
    id bigint generated by default as identity primary key,
    title text not null,
    organization text not null,
    organization_logo_url text,
    notice_type text not null check (notice_type in ('exam_schedule', 'admit_card', 'result', 'other')),
    published_date date,
    exam_date date,
    description text,
    source text not null,
    source_url text not null,
    circular_url text,
    is_active boolean default true not null,
    external_id text unique not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null,
    unique (source, source_url)
);

CREATE INDEX IF NOT EXISTS idx_exam_notices_published ON exam_notices(published_date DESC);
CREATE INDEX IF NOT EXISTS idx_exam_notices_exam_date ON exam_notices(exam_date);
ALTER TABLE exam_notices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public exam notice read access" ON exam_notices;
CREATE POLICY "Allow public exam notice read access"
    ON exam_notices FOR SELECT TO anon, authenticated USING (true);

DROP TRIGGER IF EXISTS update_exam_notices_modtime ON exam_notices;
CREATE TRIGGER update_exam_notices_modtime
    BEFORE UPDATE ON exam_notices
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();
