import { AlertCircle, Bell, ChevronRight, FileText, Globe2, Info, Mail, Moon, ShieldCheck } from 'lucide-react-native';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { AppHeader } from '@/components/layout/AppHeader';
import { ScreenContainer } from '@/components/ui/ScreenContainer';
import { colors } from '@/constants/colors';
import { radius } from '@/constants/layout';

export default function MoreScreen() {
  const comingSoon = () => Alert.alert('শিগগিরই আসছে', 'এই সুবিধাটি ভবিষ্যৎ সংস্করণের জন্য প্রস্তুত রাখা হয়েছে।');
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content}><AppHeader title="আরও" subtitle="অ্যাপ সেটিংস ও প্রয়োজনীয় তথ্য" />
    <View style={styles.brand}><View style={styles.logo}><Text style={styles.logoText}>জব</Text></View><View style={{ flex: 1 }}><Text style={styles.brandTitle}>সরকারি চাকরি</Text><Text style={styles.brandText}>বাংলাদেশের সরকারি চাকরি এক জায়গায়</Text></View></View>
    <Section title="পছন্দ"><MenuRow icon={Globe2} label="ভাষা" value="বাংলা" onPress={comingSoon} /><MenuRow icon={Bell} label="নোটিফিকেশন" value="শিগগিরই" onPress={comingSoon} /><MenuRow icon={Moon} label="ডার্ক মোড" trailing={<Switch disabled value={false} trackColor={{ false: colors.border, true: colors.primaryLight }} />} /></Section>
    <Section title="তথ্য"><MenuRow icon={Info} label="অ্যাপ সম্পর্কে" onPress={() => Alert.alert('সরকারি চাকরি', 'সংস্করণ ১.০.০\nসরকারি চাকরির বিজ্ঞপ্তি সহজে খুঁজে পাওয়ার জন্য তৈরি।')} /><MenuRow icon={ShieldCheck} label="তথ্যসূত্র" onPress={() => Alert.alert('তথ্যসূত্র', 'চাকরির তথ্য সংশ্লিষ্ট সরকারি প্রতিষ্ঠানের অফিসিয়াল প্রকাশনা থেকে সংগ্রহ করা হয়।')} /><MenuRow icon={FileText} label="গোপনীয়তা নীতি" onPress={comingSoon} /><MenuRow icon={Mail} label="যোগাযোগ" onPress={comingSoon} /></Section>
    <View style={styles.disclaimer}><AlertCircle size={18} color={colors.textSecondary} /><View style={{ flex: 1 }}><Text style={styles.disclaimerTitle}>ডিসক্লেইমার</Text><Text style={styles.disclaimerText}>এই অ্যাপটি প্রকাশ্যে পাওয়া সরকারি চাকরির তথ্য একত্র করে। এটি বাংলাদেশ সরকারের অফিসিয়াল অ্যাপ নয়। আবেদন করার আগে অফিসিয়াল বিজ্ঞপ্তি যাচাই করুন।</Text></View></View>
    <Text style={styles.version}>সরকারি চাকরি • সংস্করণ ১.০.০</Text>
  </ScrollView></ScreenContainer>;
}

function Section({ title, children }: React.PropsWithChildren<{ title: string }>) { return <View style={styles.sectionWrap}><Text style={styles.sectionLabel}>{title}</Text><View style={styles.section}>{children}</View></View>; }
function MenuRow({ icon: Icon, label, value, trailing, onPress }: { icon: typeof Info; label: string; value?: string; trailing?: React.ReactNode; onPress?: () => void }) { return <Pressable disabled={!onPress} onPress={onPress} style={({ pressed }) => [styles.row, pressed && { opacity: 0.7 }]}><View style={styles.rowIcon}><Icon size={19} color={colors.primary} /></View><Text style={styles.rowLabel}>{label}</Text>{value ? <Text style={styles.rowValue}>{value}</Text> : null}{trailing ?? (onPress ? <ChevronRight size={19} color={colors.textSecondary} /> : null)}</Pressable>; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 34, gap: 22 }, brand: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 17, borderRadius: radius.lg, backgroundColor: colors.primaryDeep }, logo: { width: 52, height: 52, borderRadius: 16, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, logoText: { color: colors.primary, fontSize: 17, fontWeight: '900' }, brandTitle: { color: '#fff', fontSize: 18, fontWeight: '800' }, brandText: { color: '#D6E8E2', fontSize: 12, marginTop: 4 }, sectionWrap: { gap: 9 }, sectionLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '700', marginLeft: 4 }, section: { overflow: 'hidden', borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card }, row: { minHeight: 58, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, rowIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: colors.primaryLight, alignItems: 'center', justifyContent: 'center' }, rowLabel: { flex: 1, color: colors.text, fontSize: 14, fontWeight: '600' }, rowValue: { color: colors.textSecondary, fontSize: 12 }, disclaimer: { flexDirection: 'row', gap: 10, padding: 16, backgroundColor: '#F0F3F1', borderRadius: radius.lg }, disclaimerTitle: { color: colors.text, fontSize: 14, fontWeight: '700' }, disclaimerText: { color: colors.textSecondary, fontSize: 12, lineHeight: 19, marginTop: 5 }, version: { color: colors.textSecondary, textAlign: 'center', fontSize: 11 } });
